http {
    include /etc/nginx/snippets/ruconet-http.conf;

    # Bluesky PDS
    server {
        listen pds.ruconet.internal:443 ssl;

        include /etc/nginx/snippets/ruconet.conf;
        include /etc/nginx/snippets/ruconet-gateway.conf;

        client_max_body_size    300m;
        proxy_request_buffering off;

        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;

        location / {
            proxy_pass http://127.0.0.1:3000;
            include /etc/nginx/snippets/ruconet-forward.conf;
        }
    }
}
