stream {
    include /etc/nginx/snippets/ruconet-stream.conf;

    # Submission (Client)
    server {
        listen 127.0.0.1:587;

        proxy_pass mail.ruconet.internal:587;
        proxy_timeout 30m;

        proxy_ssl on;
        include /etc/nginx/snippets/ruconet-proxy.conf;
    }
}
